### PR TITLE
Added an exclude query option

### PR DESCRIPTION
**Pull request by ericmatthys**
I have found it annoying working around issues related to webpack resolving a helper as an unrelated module in `node_modules`. `{{path}}` or `{{url}}` are common culprits. The only current workarounds seem to be renaming them or using `{{this.path}}`. I think it would be common to only want to use helpers and partials within the project and ignore anything that might resolve to a module in `node_modules`.

There is a possibility that the naming collision with the loader-level `exclude` is confusing. I had trouble thinking of a good name for the option, but maybe you'll have a better idea.

Example:

```js
query: {
  exclude: 'node_modules',
  helperDirs: ['app/helpers']
}
```

### CODE REVIEW

**Comment by ericmatthys** [comment]
Related: https://github.com/altano/handlebars-loader/issues/41

**Comment by altano** [comment]
Looks good to me.  I'm soliciting feedback in https://github.com/altano/handlebars-loader/issues/41.  In the meantime, can you add a unit test for this?

**Comment by altano** [comment]
And thanks for fixing the issue :)

**Comment by altano** [comment]
Oh, and one last comment for now: please update the README.md to reflect the new parameter.

Thanks!

**Comment by altano** [comment]
In handlebars-loader@1.1.4 on npm.  Thanks.

**Comment by ericmatthys** [comment]
A README update and unit test are in the PR already. Is there something specific you want different?

**Comment by altano** [comment]
Sorry, those last two comments must have been meant for another PR.  I deleted them to reduce further confusion.

Some follow-up questions:
1. Should excluding node_modules be the default?
2. Should 'exclude' be an array of regexes?
3. Would 'moduleExcludes' or 'helperModuleExcludes' be a better name?  I think it's not obvious what is being excluded with the current name.  *shrug*

**Comment by ericmatthys** [comment]
> Should excluding node_modules be the default?

This could break existing setups, so it would require a major version bump. I do think it's a reasonable default though.

> Should 'exclude' be an array of regexes?

A single regex should be enough imo. The expression can always be made to include multiple directories.

> I think it's not obvious what is being excluded with the current name.

Agreed. `helperExcludes` lines up with `helperDirs` nicely.

**Comment by ericmatthys** [comment]
@altano What do you think needs to happen to progress this?

**Comment by ianbytchek** [comment]
@ericmatthys @altano a gentle reminder.

**Comment by rakeshmenon** [comment]
@altano is there any open question on this?

**Comment by pcardune** [comment]
Looks good to me! Thanks for the contribution. I'm going through all the outstanding pull requests and will make a new release soon.

**Pull request merged**
