### PR TITLE
Added query option `knownHelpersOnly`

### PR DESCRIPTION
**Pull request by damassi**
When set to `false`, it overrides the default lookup scan so that you can define helpers easily post compile-time (aka, unknown helpers).  This is useful when complex helper logic is defined outside of the compiler or lookup paths cannot be easily specified.

### CODE REVIEW

**Comment by altano** [comment]
2 things:

1) Can you add a test that exercises this option?
2) I don't understand how you would use this option, but of course I'm totally amenable to adding it if you need it.  Could you explain how you would use this?

**Comment by damassi** [comment]
@altano - Sure thing, I'll get to that today.

**Comment by damassi** [comment]
@altano, I've updated the PR to include tests (see 084baa73bcd81d1e1ca06ad709fad42b217eeef2).  The `knownHelpersOnly` query param corresponds to the Handlebars api located here:  http://handlebarsjs.com/reference.html.  

What this does is allow for Handlebars helpers to be added during runtime as opposed to compile-time; meaning, by default, when the hbs compiler is run, it will analyze all helpers located in the code and, if it finds one, will validate, and if a helper is defined that it cannot find it will throw an error and exit compilation.  When `knownHelpersOnly` is set to `false`, it will skip this check and instead rely upon the `handlebars/runtime` to validate during the execution of the application.  

This is useful for applications that define complex helper logic that must exist outside of compiler or node in general (for example, dynamically defining a helper that is returned based upon the result of an API request.)

Hope this clarifies a bit.

**Comment by altano** [comment]
That makes sense and I get it now.  Should definitely be used with caution since it doesn't allow compile-time module loading of all the dependencies by webpack.

One more thing: do you have time to add a negative test?  We don't have a test that makes sure the compile fails if the template references an unknown helper, when this setting is *not* set.  I'll take the PR with or without the test but would appreciate your adding it if you can.

**Comment by altano** [comment]
@kpdecker can you confirm this resolves https://github.com/altano/handlebars-loader/issues/17 for you? That it fulfills your need?

**Comment by kpdecker** [comment]
@altano not really. This avoids the error at the expense of dramatically larger and slower templates for the cases where we have known helpers that can not be seeded.

**Comment by damassi** [comment]
@altano -- Definitely agree that it should be used with caution, though there are a number of situations where this flexibility could be useful, particularly with older webapps.  

Will write a negative test first thing tomorrow.

**Comment by damassi** [comment]
@altano - Sorry for the delay, i've been super slammed at work!  

I've updated tests with failing results but I'm running into problems with a flag that is being used throughout for my last test, `firstCompile`.  Attempting to work around this flag is leading to brittle results, and I don't quite understand its purpose fully.  

Could you please look at https://github.com/Kindling/handlebars-loader/commit/c1275c9e2387722df4cd3a364b4a12a6c29db0d4#diff-c1129c8b045390789fa8ff62f2c6b4a9R216 where I've commented out the `assert.ok`?  If you uncomment you will see an error being thrown.  

The use-case for this additional loader option is valid and I would very much like to get this merged in, though at the moment I might need a little help.  Any thoughts would be appreciated.

**Comment by diurnalist** [comment]
Fixed by #45

**Comment by damassi** [comment]
@diurnalist - Could you explain how your implementation works in relation to the above?  I just pulled down but am getting errors, most likely due to a failure to understand.   Any help would be appreciated.

**Comment by crossjs** [comment]
need for query option "knownHelpersOnly", while i use custom helpers that defined in runtime

**Comment by attenzione** [comment]
if anyone still have issue with this, see https://github.com/pcardune/handlebars-loader/issues/118#issuecomment-363811799

**Pull request closed without merging**
